# Fashion price prediction feature definitions for Feast
#
# Defines: product entity, fashion_price_features batch source (parquet),
# FeatureView schema (17 features + price_dropped target), price_prediction FeatureService.
# Parquet is generated by scripts/generate_feast_data.py.

from datetime import timedelta

from feast import Entity, FeatureService, FeatureView, Field, FileSource
from feast.types import Float32, Float64, Int64

# Entity: product_id is the join key for feature lookup
product = Entity(
    name="product",
    join_keys=["product_id"],
    description="Fashion product identifier",
)

# Batch source: pre-computed price features (generated by scripts/generate_feast_data.py)
fashion_price_source = FileSource(
    name="fashion_price_features_source",
    path="data/fashion_price_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created",
)

# Feature view: one row per product with precomputed features; online store for low-latency lookup
fashion_price_features = FeatureView(
    name="fashion_price_features",
    entities=[product],
    ttl=timedelta(days=1),
    schema=[
        Field(name="price_min_7d", dtype=Float64),
        Field(name="price_max_7d", dtype=Float64),
        Field(name="price_mean_7d", dtype=Float64),
        Field(name="price_std_7d", dtype=Float64),
        Field(name="price_change_7d", dtype=Float64),
        Field(name="price_change_pct_7d", dtype=Float64),
        Field(name="price_volatility_7d", dtype=Float64),
        Field(name="num_price_drops_7d", dtype=Int64),
        Field(name="original_price_usd", dtype=Float64),
        Field(name="category_cat", dtype=Int64),
        Field(name="brand_cat", dtype=Int64),
        Field(name="subcategory_cat", dtype=Int64),
        Field(name="color_cat", dtype=Int64),
        Field(name="season_cat", dtype=Int64),
        Field(name="region_cat", dtype=Int64),
        Field(name="age_group_cat", dtype=Int64),
        Field(name="inventory_level", dtype=Int64, description="Inventory level 1-100"),
        Field(name="price_dropped", dtype=Int64, description="Target: 1 if price dropped"),
    ],
    online=True,
    source=fashion_price_source,
    tags={"team": "price_prediction"},
)

# Feature service: groups feature views for serving (e.g. price_prediction service)
price_prediction_service = FeatureService(
    name="price_prediction",
    features=[fashion_price_features],
    description="Features for fashion price drop prediction model",
)
